-- MySQL Script generated by MySQL Workbench
-- Sun Jul 25 15:44:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema one_more_advice
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `one_more_advice` ;

-- -----------------------------------------------------
-- Schema one_more_advice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `one_more_advice` DEFAULT CHARACTER SET utf8mb4 ;
USE `one_more_advice` ;

-- -----------------------------------------------------
-- Table `one_more_advice`.`qiita_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `one_more_advice`.`qiita_user` ;

CREATE TABLE IF NOT EXISTS `one_more_advice`.`qiita_user` (
  `user_id` VARCHAR(255) NOT NULL,
  `description` LONGTEXT NULL,
  `facebook_id` VARCHAR(255) NULL,
  `followees_count` INT(10) NULL,
  `followers_count` INT(10) NULL,
  `github_login_name` VARCHAR(50) NULL,
  `items_count` INT(10) NULL,
  `linkedin_id` VARCHAR(255) NULL,
  `location` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `organization` VARCHAR(255) NULL,
  `permanent_id` INT(10) NULL,
  `profile_image_url` VARCHAR(255) NULL,
  `team_only` TINYINT(4) NULL,
  `twitter_screen_name` VARCHAR(255) NULL,
  `website_url` VARCHAR(255) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `one_more_advice`.`qiita_tag_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `one_more_advice`.`qiita_tag_master` ;

CREATE TABLE IF NOT EXISTS `one_more_advice`.`qiita_tag_master` (
  `tag_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`tag_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `one_more_advice`.`qiita_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `one_more_advice`.`qiita_item` ;

CREATE TABLE IF NOT EXISTS `one_more_advice`.`qiita_item` (
  `item_id` VARCHAR(255) NOT NULL,
  `text` LONGTEXT NULL,
  `coediting` TINYINT(4) NULL,
  `comments_count` INT(10) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `likes_count` INT(10) NULL,
  `private` TINYINT(4) NULL,
  `reactions_count` INT(10) NULL,
  `title` VARCHAR(255) NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `url` VARCHAR(255) NULL,
  `page_views_count` INT(10) NULL,
  `user_id` VARCHAR(255) NULL,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `one_more_advice`.`qiita_item_to_tag_relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `one_more_advice`.`qiita_item_to_tag_relation` ;

CREATE TABLE IF NOT EXISTS `one_more_advice`.`qiita_item_to_tag_relation` (
  `item_id` VARCHAR(255) NULL,
  `tag_name` VARCHAR(255) NULL,
  INDEX `item_id_idx` (`item_id` ASC),
  INDEX `tag_name_idx` (`tag_name` ASC),
  CONSTRAINT `item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `one_more_advice`.`qiita_item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tag_name`
    FOREIGN KEY (`tag_name`)
    REFERENCES `one_more_advice`.`qiita_tag_master` (`tag_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
