version: "3.8"
services:
    one_more_advice_db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: one_more_advice
            MYSQL_DATABASE: one_more_advice
        ports:
            - 4306:3306
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        networks:
            one_more_advice_network:
                ipv4_address: 172.30.0.4
    data_collection:
        image: data_collection
        env_file: data_collection/.env # 開発用
        build:
            context: data_collection/
        volumes: ## 開発をするときは、コメントアウトを外すと実装がしやすくなる
            - ./data_collection/src:/home/sdk/src
            - ./data_collection/query:/home/sdk/query
            - ./data_collection/data:/home/sdk/data
        networks:
            one_more_advice_network:
                ipv4_address: 172.30.0.5

networks:
    one_more_advice_network:
        name: one_more_advice_network_db
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/24
