version: "3.8"
services:
    one_more_advice_db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: one_more_advice
            MYSQL_DATABASE: one_more_advice
        ports:
            - 4306:3306
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    data_collection:
        image: data_collection
        env_file: data_collection/.env # 開発用
        build:
            context: data_collection/
        volumes: ## 開発をするときは、コメントアウトを外すと実装がしやすくなる
            - ./data_collection/src:/home/sdk/src
            - ./data_collection/query:/home/sdk/query
            - ./data_collection/data:/home/sdk/data
