version: "3.8"
services:
    one_more_advice_db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: one_more_advice
            MYSQL_DATABASE: one_more_advice
        ports:
            - 4306:3306
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
